title: 내 이름은 다빈
email: dorothy9795@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
profile_logo: /images/profile-logo.gif

navigation:
  - name: 소개
    url: /about
  - name: 글
    url: /

footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: # dorothy9795@gmail.com
  facebook:
  flickr:
  github: MyNameIsDabin
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: 
  youtube: # channel/<your_long_string> or user/<user-name>

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
